server:
  port: 8080

spring:
  application:
    name: api-gateway

services:
  auth:
    url: http://localhost:8081
  transaction:
    url: http://localhost:8082
  payment:
    url: http://localhost:8083
