server:
  port: 8080

spring:
  application:
    name: api-gateway

services:
  auth:
    url: http://${AUTH_SERVICE_HOST:localhost}:8081
  transaction:
    url: http://${TRANSACTION_SERVICE_HOST:localhost}:8082
  payment:
    url: http://${PAYMENT_SERVICE_HOST:localhost}:8083
  account:
    url: http://${ACCOUNT_SERVICE_HOST:localhost}:8084

cors:
  allowed-origin: http://${FRONTEND_SERVICE_HOST:localhost}:3000
