server:
  port: 8084

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}?currentSchema=banking_accounts&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: banking_accounts
        format_sql: true

services:
  transaction:
    url: http://localhost:8082